@startuml

!include ../style.puml
box Logic LOGIC_COLOR_T1
participant ":**FindClientCommand**" as FindClientCommand LOGIC_COLOR
participant "**r:CommandResult**" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "**m:Model**" as Model MODEL_COLOR
end box

[-> FindClientCommand : ""execute(m)""
activate FindClientCommand

note right
""p"" is the Predicate
that checks if the given
end note

FindClientCommand -> Model : ""updateFilteredClientList(p)""
activate Model

Model --> FindClientCommand
deactivate Model

create CommandResult
FindClientCommand -> CommandResult
activate CommandResult

CommandResult --> FindClientCommand : ""r""
deactivate CommandResult

[<-- FindClientCommand : ""r""
deactivate FindClientCommand

FindClientCommand -[hidden]> CommandResult
destroy FindClientCommand

@enduml
