@startuml
!include ../style.puml

box Logic LOGIC_COLOR_T1
participant ":**ClearRevenueCommand**" as ClearRevenueCommand LOGIC_COLOR
participant "**r:CommandResult**" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "**m:ModelManager**" as ModelManager MODEL_COLOR
participant "**e:RevenueTracker**" as RevenueTracker MODEL_COLOR
participant "**:NonUniqueList**" as NonUniqueList MODEL_COLOR
end box

[-> ClearRevenueCommand : ""execute(m, h)""
activate ClearRevenueCommand

note right
""h"" refers to the HistoryManager
which keeps track of the history of
commands executed.
end note

ClearRevenueCommand -> ModelManager : ""setRevenues()""
activate ModelManager

ModelManager -> RevenueTracker: ""setRevenues()""
activate RevenueTracker
RevenueTracker -> NonUniqueList: ""setItems()""
activate NonUniqueList
RevenueTracker <-- NonUniqueList: """"
deactivate NonUniqueList
ModelManager <-- RevenueTracker: """"
deactivate RevenueTracker

create CommandResult
ModelManager --> CommandResult: """"
deactivate ModelManager
activate CommandResult
ClearRevenueCommand <-- CommandResult: ""r""
deactivate CommandResult

[<-- ClearRevenueCommand: ""r""

@enduml




