@startuml

!include ../style.puml
title Adding a Service

start

:Receives an ""addsvc"" command;

if () then ([valid command])
      :Parses the
      ""addsvc"" command
      and the parameters;

      if () then ([less than 1000 services in Homerce])
      :Generate new unique service code;

      :Add the new service to Homerce;

      :Shows a success message;

      else ([else])

      :Shows maximum number of services added
      error message;

      endif

else ([else])

    :Shows an
    invalid command
    error message;
endif

stop

@enduml
