@startuml
!include ../style.puml

box Logic LOGIC_COLOR_T1
participant ":**AddServiceCommand**" as AddServiceCommand LOGIC_COLOR
participant "**r:CommandResult**" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "**m:ModelManager**" as ModelManager MODEL_COLOR
participant "**:ServiceCodeGenerator**" as ServiceCodeGenerator MODEL_COLOR
participant "**:ServiceManager**" as ServiceManager MODEL_COLOR
participant "**:AppointmentManager**" as AppointmentManager MODEL_COLOR
end box

[-> AddServiceCommand : ""execute(m, h)""
activate AddServiceCommand

note right
""h"" refers to the HistoryManager
which keeps track of the history of
commands executed.
end note

AddServiceCommand -> ModelManager : ""getServiceManager()""
activate ModelManager
AddServiceCommand <-- ModelManager: ""sm""
deactivate ModelManager

AddServiceCommand -> ServiceManager : ""getServiceList()""
activate ServiceManager
AddServiceCommand <-- ServiceManager : ""services""
deactivate ServiceManager

AddServiceCommand -> ModelManager : ""getAppointmentManager()""
activate ModelManager
AddServiceCommand <-- ModelManager: ""am""
deactivate ModelManager

AddServiceCommand -> AppointmentManager : ""getAppointmentList()""
activate AppointmentManager
AddServiceCommand <-- AppointmentManager : ""appointments""
deactivate AppointmentManager

AddServiceCommand -> ServiceCodeGenerator: ""generateServiceCode(services, appointments)""

activate ServiceCodeGenerator
AddServiceCommand <-- ServiceCodeGenerator: ""serviceCode""
deactivate ServiceCodeGenerator

AddServiceCommand -> ModelManager : ""addService(s)""
activate ModelManager

ModelManager -> ServiceManager: ""addService(s)""
activate ServiceManager

ServiceManager --> ModelManager
deactivate ServiceManager

ModelManager --> AddServiceCommand
deactivate ModelManager

create CommandResult
AddServiceCommand -> CommandResult
activate CommandResult

CommandResult --> AddServiceCommand : ""r""
deactivate CommandResult

[<-- AddServiceCommand : ""r""
deactivate AddServiceCommand

AddServiceCommand -[hidden]> CommandResult

@enduml
